### ISSUE TITLE
Weirdly long inference time using cuda? Much much slower

### ISSUE THREAD

**Issue by Jasonzhangzzf** [jingsongliujing/OnnxOCR#14]
Environment: 
python=3.11
Ubuntu 22.04
cuda = 11.8
cudnn = 8.7
onnxruntime-gpu = 1.17
tensor rt = 8.6

1. use_gpu=False
![Screenshot 2024-07-17 at 3 48 52 PM](https://github.com/user-attachments/assets/6c7355d6-f25f-4a49-90d0-5dbbcb2fd8b7)
2. use_gpu=True
![Screenshot 2024-07-17 at 4 06 29 PM](https://github.com/user-attachments/assets/d6498849-d13b-42a6-9cbb-e991b901e29c)

Is it due to warnings and probably onnxruntime-gpu library version differences?

**Comment by Jasonzhangzzf** [comment]
The corresponding environment matches what is recommended by the onnxruntime-gpu page.
<img width="1158" alt="Screenshot 2024-07-17 at 4 02 34 PM" src="https://github.com/user-attachments/assets/ef53ea37-51e0-4a56-be46-844c4c9bd2b5">

**Comment by jingsongliujing** [comment]
Regarding ppocrv4, I have only tested it on CPU. ONNX Runtime may not implement certain operators for CUDA or other reasons.

**Comment by Jasonzhangzzf** [comment]
Ok then. So CPU inference only. Thanks for the reply!
