### ISSUE TITLE
这个代码可以商用吗?

### ISSUE THREAD

**Issue by zhangningboo** [jingsongliujing/OnnxOCR#23]
大佬，这个repo的代码，我可以商用吗？商用有限制吗？

**Comment by jingsongliujing** [comment]
目前是Apache协议，没有限制，假如项目对您有帮助，请点个赞



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jingsongliujing/OnnxOCR] 这个代码可以商用吗? (Issue #23)




 
大佬，这个repo的代码，我可以商用吗？商用有限制吗？

**Comment by jingsongliujing** [comment]
也欢迎您加入我创建的社群，大家一起把onnxocr生态做的更好: liujingsongweixin



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jingsongliujing/OnnxOCR] 这个代码可以商用吗? (Issue #23)




 
大佬，这个repo的代码，我可以商用吗？商用有限制吗？

**Comment by zhangningboo** [comment]
ok
