### ISSUE TITLE
大佬你好，你的教程里面用的v2.0的模型，问一下v3和v4可以吗，预处理和后处理有没有区别

### ISSUE THREAD

**Issue by ccl-private** [jingsongliujing/OnnxOCR#3]
如题

**Comment by jingsongliujing** [comment]
v3和v4需要修改前后处理，这个有时间我再做个兼容

**Comment by ccl-private** [comment]
好的，给星关注～

**Comment by ccl-private** [comment]
我成功将V3跑起来了，v3的rec模型输入高度是48,v2是32。
先将./onnx/util.py里面参数修改parser.add_argument("--rec_image_shape", type=str, default="3, 48, 320")
然后将./onnx/onnx_paddleocr.py里面这一行注释params.rec_image_shape = "3, 32, 320"

**Comment by jingsongliujing** [comment]
OK，感谢

**Comment by jingsongliujing** [comment]
但是实际上我们也试过v3，OCR的中文识别精度不如v2的server版本，v4的话精度虽然比较高，但推理速度上又比较慢，相比之下，v2的server版本是一个速度和精度都比较不错的版本选择

**Comment by jingsongliujing** [comment]
我已经更新到ppocrv4版本的推理，比paddlepaddle框架直接推理快五倍

**Comment by ccl-private** [comment]
厉害

**Comment by awaqq520** [comment]
> 我已经更新到ppocrv4版本的推理，比paddlepaddle框架直接推理快五倍

可以将它部署到c++环境中嘛,我弄了onnxruntime静态库和opencv静态库,我想生成一个,不依赖于环境的(只需要onnx和exe就可以进行预测)
